### ISSUE TITLE
Problem on `statsCounts['All sgRNAs uniquely map'] ` is 0

### ISSUE THREAD

**Issue by wook2014** [josephreplogle/CRISPRi-dual-sgRNA-screens#4]
I have run the `dualguide_fastqgz_to_counts.py` and meet up with a problem about 
```
File "/home/wook/dualguide_fastqgz_to_counts.py", line 92, in writeToCounts
print('Percent A sgRNA and B sgRNA mismatch', statsCounts['A sgRNA and B sgRNA do not match'] * 100.0 / statsCounts['All sgRNAs uniquely map'])
ZeroDivisionError: float division by zero
```
It seemed that this problem is caused by `statsCounts['All sgRNAs uniquely map'] ` is 0. The problem is in line 92 93. Should there be a `if statsCounts['All sgRNAs uniquely map'] != 0:` to avoid such situation?

**Comment by josephreplogle** [comment]
Yes, it could make sense to add that line to avoid this error. However, in all cases where I have used the script, if 0 reads are mapping, there is a larger problem and I think it is useful to throw an error. Generally this is because the sequencing parameters does not match the trimming and library file.
